/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

static void pose_mode_button_27_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create robot_home
        robot_home_create(&ui_manager);
        // load robot_home
        lv_scr_load_anim(robot_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, true);
    }
}

static void pose_mode_spinbox_32_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(pose_mode_get(&ui_manager)->spinbox_32);
    }
}

static void pose_mode_spinbox_32_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(pose_mode_get(&ui_manager)->spinbox_32);
    }
}

static void pose_mode_spinbox_33_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(pose_mode_get(&ui_manager)->spinbox_33);
    }
}

static void pose_mode_spinbox_33_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(pose_mode_get(&ui_manager)->spinbox_33);
    }
}

static void pose_mode_spinbox_34_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(pose_mode_get(&ui_manager)->spinbox_34);
    }
}

static void pose_mode_spinbox_34_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(pose_mode_get(&ui_manager)->spinbox_34);
    }
}

static void pose_mode_spinbox_35_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(pose_mode_get(&ui_manager)->spinbox_35);
    }
}

static void pose_mode_spinbox_35_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(pose_mode_get(&ui_manager)->spinbox_35);
    }
}

static void pose_mode_spinbox_36_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(pose_mode_get(&ui_manager)->spinbox_36);
    }
}

static void pose_mode_spinbox_36_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(pose_mode_get(&ui_manager)->spinbox_36);
    }
}

static void pose_mode_spinbox_37_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(pose_mode_get(&ui_manager)->spinbox_37);
    }
}

static void pose_mode_spinbox_37_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(pose_mode_get(&ui_manager)->spinbox_37);
    }
}


void pose_mode_create(ui_manager_t *ui)
{
    pose_mode_t *scr = pose_mode_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x003a57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_27
    scr->button_27 = lv_btn_create(scr->obj);
    lv_obj_t *button_27_label = lv_label_create(scr->button_27);
    lv_label_set_text(button_27_label, "back");
    lv_obj_align(button_27_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_27, 6, 228);
    lv_obj_set_size(scr->button_27, 54, 35);
    lv_obj_add_flag(scr->button_27, LV_OBJ_FLAG_FLOATING);

    // Set style of scr->button_27
    lv_obj_set_style_text_font(scr->button_27, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->button_27, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_27, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_27
    lv_obj_add_event_cb(scr->button_27, pose_mode_button_27_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->pos_set_mode_TXT
    scr->pos_set_mode_TXT = lv_textarea_create(scr->obj);
    lv_textarea_set_one_line(scr->pos_set_mode_TXT, true);
    lv_textarea_set_text(scr->pos_set_mode_TXT, "Axis_Robot Pos Set mode");
    lv_textarea_set_placeholder_text(scr->pos_set_mode_TXT, "");
    lv_obj_set_pos(scr->pos_set_mode_TXT, 71, -8);
    lv_obj_set_size(scr->pos_set_mode_TXT, 337, 50);

    // Set style of scr->pos_set_mode_TXT
    lv_obj_set_style_bg_opa(scr->pos_set_mode_TXT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->pos_set_mode_TXT, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->pos_set_mode_TXT, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->pos_set_mode_TXT, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->pos_set_mode_TXT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->menu_6
    scr->menu_6 = lv_menu_create(scr->obj);
    lv_obj_t *pose_mode_menu_6_sidebar = lv_menu_page_create(scr->menu_6, NULL);
    lv_menu_set_sidebar_page(scr->menu_6, pose_mode_menu_6_sidebar);
    lv_obj_t *pose_mode_menu_6_sidebar_header = lv_menu_get_sidebar_header(scr->menu_6);
    lv_obj_add_flag(pose_mode_menu_6_sidebar_header, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *menu_6_main_header = lv_menu_get_main_header(scr->menu_6);
    lv_obj_add_flag(menu_6_main_header, LV_OBJ_FLAG_HIDDEN);

    lv_obj_t *pose_mode_menu_6_page_1 = lv_menu_page_create(scr->menu_6, NULL);
    lv_obj_t *pose_mode_menu_6_cont_1 = lv_menu_cont_create(pose_mode_menu_6_sidebar);
    lv_obj_t *pose_mode_menu_6_cont_1_lab = lv_label_create(pose_mode_menu_6_cont_1);
    lv_label_set_text(pose_mode_menu_6_cont_1_lab, "X");
    lv_menu_set_load_page_event(scr->menu_6, pose_mode_menu_6_cont_1, pose_mode_menu_6_page_1);

    lv_obj_t *pose_mode_menu_6_page_2 = lv_menu_page_create(scr->menu_6, NULL);
    lv_obj_t *pose_mode_menu_6_cont_2 = lv_menu_cont_create(pose_mode_menu_6_sidebar);
    lv_obj_t *pose_mode_menu_6_cont_2_lab = lv_label_create(pose_mode_menu_6_cont_2);
    lv_label_set_text(pose_mode_menu_6_cont_2_lab, "Y");
    lv_menu_set_load_page_event(scr->menu_6, pose_mode_menu_6_cont_2, pose_mode_menu_6_page_2);

    lv_obj_t *pose_mode_menu_6_page_3 = lv_menu_page_create(scr->menu_6, NULL);
    lv_obj_t *pose_mode_menu_6_cont_3 = lv_menu_cont_create(pose_mode_menu_6_sidebar);
    lv_obj_t *pose_mode_menu_6_cont_3_lab = lv_label_create(pose_mode_menu_6_cont_3);
    lv_label_set_text(pose_mode_menu_6_cont_3_lab, "Z");
    lv_menu_set_load_page_event(scr->menu_6, pose_mode_menu_6_cont_3, pose_mode_menu_6_page_3);

    lv_obj_t *pose_mode_menu_6_page_4 = lv_menu_page_create(scr->menu_6, NULL);
    lv_obj_t *pose_mode_menu_6_cont_4 = lv_menu_cont_create(pose_mode_menu_6_sidebar);
    lv_obj_t *pose_mode_menu_6_cont_4_lab = lv_label_create(pose_mode_menu_6_cont_4);
    lv_label_set_text(pose_mode_menu_6_cont_4_lab, "Roll");
    lv_menu_set_load_page_event(scr->menu_6, pose_mode_menu_6_cont_4, pose_mode_menu_6_page_4);

    lv_obj_t *pose_mode_menu_6_page_5 = lv_menu_page_create(scr->menu_6, NULL);
    lv_obj_t *pose_mode_menu_6_cont_5 = lv_menu_cont_create(pose_mode_menu_6_sidebar);
    lv_obj_t *pose_mode_menu_6_cont_5_lab = lv_label_create(pose_mode_menu_6_cont_5);
    lv_label_set_text(pose_mode_menu_6_cont_5_lab, "Pitch");
    lv_menu_set_load_page_event(scr->menu_6, pose_mode_menu_6_cont_5, pose_mode_menu_6_page_5);

    lv_obj_t *pose_mode_menu_6_page_6 = lv_menu_page_create(scr->menu_6, NULL);
    lv_obj_t *pose_mode_menu_6_cont_6 = lv_menu_cont_create(pose_mode_menu_6_sidebar);
    lv_obj_t *pose_mode_menu_6_cont_6_lab = lv_label_create(pose_mode_menu_6_cont_6);
    lv_label_set_text(pose_mode_menu_6_cont_6_lab, "Yaw");
    lv_menu_set_load_page_event(scr->menu_6, pose_mode_menu_6_cont_6, pose_mode_menu_6_page_6);

#if LVGL_VERSION_MAJOR == 8
    lv_event_send(pose_mode_menu_6_cont_1, LV_EVENT_CLICKED, NULL);
#else
    lv_obj_send_event(pose_mode_menu_6_cont_1, LV_EVENT_CLICKED, NULL);
#endif
    lv_obj_set_pos(scr->menu_6, 5, 35);
    lv_obj_set_size(scr->menu_6, 471, 189);

    // Set style of scr->menu_6
    lv_obj_set_style_bg_color(scr->menu_6, lv_color_hex(0xe6e6e6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->menu_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(pose_mode_menu_6_cont_1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(pose_mode_menu_6_cont_1, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(pose_mode_menu_6_cont_2, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(pose_mode_menu_6_cont_2, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(pose_mode_menu_6_cont_3, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(pose_mode_menu_6_cont_3, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(pose_mode_menu_6_cont_4, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(pose_mode_menu_6_cont_4, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(pose_mode_menu_6_cont_5, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(pose_mode_menu_6_cont_5, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(pose_mode_menu_6_cont_6, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(pose_mode_menu_6_cont_6, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);

    // Init scr->container_21
    scr->container_21 = lv_obj_create(pose_mode_menu_6_page_1);
    lv_obj_set_pos(scr->container_21, 5, 0);
    lv_obj_set_size(scr->container_21, 319, 184);
    lv_obj_set_scrollbar_mode(scr->container_21, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_21
    lv_obj_set_style_bg_color(scr->container_21, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->container_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->textarea_30
    scr->textarea_30 = lv_textarea_create(scr->container_21);
    lv_textarea_set_one_line(scr->textarea_30, false);
    lv_textarea_set_text(scr->textarea_30, "X limit:\n-549 to 546mm\nReset: 340.45mm");
    lv_textarea_set_placeholder_text(scr->textarea_30, "");
    lv_obj_set_pos(scr->textarea_30, 14, 18);
    lv_obj_set_size(scr->textarea_30, 130, 105);

    // Set style of scr->textarea_30
    lv_obj_set_style_text_font(scr->textarea_30, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_32
    scr->spinbox_32 = lv_spinbox_create(scr->container_21);

    lv_spinbox_set_range(scr->spinbox_32, -180, 180);
    lv_spinbox_set_step(scr->spinbox_32, 1);
    lv_spinbox_set_digit_format(scr->spinbox_32, 4, 3);
    lv_obj_set_pos(scr->spinbox_32, 203, 65);
    lv_obj_set_size(scr->spinbox_32, 72, 40);

    scr->spinbox_32_left_btn = lv_btn_create(scr->container_21);
    lv_obj_set_size(scr->spinbox_32_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_32_left_btn, scr->spinbox_32, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_32_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_32_left_btn, pose_mode_spinbox_32_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_32_right_btn = lv_btn_create(scr->container_21);
    lv_obj_set_size(scr->spinbox_32_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_32_right_btn, scr->spinbox_32, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_32_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_32_right_btn, pose_mode_spinbox_32_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_32
    lv_obj_set_style_text_font(scr->spinbox_32, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_32, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_32, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_32, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_11
    scr->slider_11 = lv_slider_create(scr->container_21);
    lv_slider_set_range(scr->slider_11, -549, 546);
    lv_slider_set_value(scr->slider_11, 340, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_11, 32, 155);
    lv_obj_set_size(scr->slider_11, 260, 13);

    // Init scr->container_22
    scr->container_22 = lv_obj_create(pose_mode_menu_6_page_2);
    lv_obj_set_pos(scr->container_22, 5, 0);
    lv_obj_set_size(scr->container_22, 319, 184);
    lv_obj_set_scrollbar_mode(scr->container_22, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_22
    lv_obj_set_style_bg_color(scr->container_22, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->container_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->textarea_31
    scr->textarea_31 = lv_textarea_create(scr->container_22);
    lv_textarea_set_one_line(scr->textarea_31, false);
    lv_textarea_set_text(scr->textarea_31, "Y limit:\n-550 to 546mm\nReset: 0mm");
    lv_textarea_set_placeholder_text(scr->textarea_31, "");
    lv_obj_set_pos(scr->textarea_31, 14, 18);
    lv_obj_set_size(scr->textarea_31, 130, 105);

    // Set style of scr->textarea_31
    lv_obj_set_style_text_font(scr->textarea_31, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_33
    scr->spinbox_33 = lv_spinbox_create(scr->container_22);

    lv_spinbox_set_range(scr->spinbox_33, -180, 180);
    lv_spinbox_set_step(scr->spinbox_33, 1);
    lv_spinbox_set_digit_format(scr->spinbox_33, 4, 3);
    lv_obj_set_pos(scr->spinbox_33, 203, 65);
    lv_obj_set_size(scr->spinbox_33, 72, 40);

    scr->spinbox_33_left_btn = lv_btn_create(scr->container_22);
    lv_obj_set_size(scr->spinbox_33_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_33_left_btn, scr->spinbox_33, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_33_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_33_left_btn, pose_mode_spinbox_33_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_33_right_btn = lv_btn_create(scr->container_22);
    lv_obj_set_size(scr->spinbox_33_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_33_right_btn, scr->spinbox_33, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_33_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_33_right_btn, pose_mode_spinbox_33_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_33
    lv_obj_set_style_text_font(scr->spinbox_33, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_33, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_33, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_33, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_12
    scr->slider_12 = lv_slider_create(scr->container_22);
    lv_slider_set_range(scr->slider_12, -550, 546);
    lv_slider_set_value(scr->slider_12, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_12, 32, 155);
    lv_obj_set_size(scr->slider_12, 260, 13);

    // Init scr->container_23
    scr->container_23 = lv_obj_create(pose_mode_menu_6_page_3);
    lv_obj_set_pos(scr->container_23, 5, 0);
    lv_obj_set_size(scr->container_23, 319, 184);
    lv_obj_set_scrollbar_mode(scr->container_23, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_23
    lv_obj_set_style_bg_color(scr->container_23, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->textarea_32
    scr->textarea_32 = lv_textarea_create(scr->container_23);
    lv_textarea_set_one_line(scr->textarea_32, false);
    lv_textarea_set_text(scr->textarea_32, "Z limit:\n0 to 600mm\nReset: 295.45mm");
    lv_textarea_set_placeholder_text(scr->textarea_32, "");
    lv_obj_set_pos(scr->textarea_32, 14, 18);
    lv_obj_set_size(scr->textarea_32, 130, 105);

    // Set style of scr->textarea_32
    lv_obj_set_style_text_font(scr->textarea_32, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_34
    scr->spinbox_34 = lv_spinbox_create(scr->container_23);

    lv_spinbox_set_range(scr->spinbox_34, -180, 180);
    lv_spinbox_set_step(scr->spinbox_34, 1);
    lv_spinbox_set_digit_format(scr->spinbox_34, 4, 3);
    lv_obj_set_pos(scr->spinbox_34, 203, 65);
    lv_obj_set_size(scr->spinbox_34, 72, 40);

    scr->spinbox_34_left_btn = lv_btn_create(scr->container_23);
    lv_obj_set_size(scr->spinbox_34_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_34_left_btn, scr->spinbox_34, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_34_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_34_left_btn, pose_mode_spinbox_34_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_34_right_btn = lv_btn_create(scr->container_23);
    lv_obj_set_size(scr->spinbox_34_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_34_right_btn, scr->spinbox_34, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_34_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_34_right_btn, pose_mode_spinbox_34_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_34
    lv_obj_set_style_text_font(scr->spinbox_34, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_34, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_34, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_34, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_13
    scr->slider_13 = lv_slider_create(scr->container_23);
    lv_slider_set_range(scr->slider_13, 0, 600);
    lv_slider_set_value(scr->slider_13, 295, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_13, 32, 155);
    lv_obj_set_size(scr->slider_13, 260, 13);

    // Init scr->container_24
    scr->container_24 = lv_obj_create(pose_mode_menu_6_page_4);
    lv_obj_set_pos(scr->container_24, 5, 0);
    lv_obj_set_size(scr->container_24, 319, 184);
    lv_obj_set_scrollbar_mode(scr->container_24, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_24
    lv_obj_set_style_bg_color(scr->container_24, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->container_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->textarea_33
    scr->textarea_33 = lv_textarea_create(scr->container_24);
    lv_textarea_set_one_line(scr->textarea_33, false);
    lv_textarea_set_text(scr->textarea_33, "Roll limit:\n-180°  to 180°\nReset:\n0°");
    lv_textarea_set_placeholder_text(scr->textarea_33, "");
    lv_obj_set_pos(scr->textarea_33, 14, 18);
    lv_obj_set_size(scr->textarea_33, 130, 105);

    // Set style of scr->textarea_33
    lv_obj_set_style_text_font(scr->textarea_33, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_35
    scr->spinbox_35 = lv_spinbox_create(scr->container_24);

    lv_spinbox_set_range(scr->spinbox_35, -180, 180);
    lv_spinbox_set_step(scr->spinbox_35, 1);
    lv_spinbox_set_digit_format(scr->spinbox_35, 4, 3);
    lv_obj_set_pos(scr->spinbox_35, 203, 65);
    lv_obj_set_size(scr->spinbox_35, 72, 40);

    scr->spinbox_35_left_btn = lv_btn_create(scr->container_24);
    lv_obj_set_size(scr->spinbox_35_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_35_left_btn, scr->spinbox_35, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_35_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_35_left_btn, pose_mode_spinbox_35_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_35_right_btn = lv_btn_create(scr->container_24);
    lv_obj_set_size(scr->spinbox_35_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_35_right_btn, scr->spinbox_35, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_35_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_35_right_btn, pose_mode_spinbox_35_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_35
    lv_obj_set_style_text_font(scr->spinbox_35, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_35, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_35, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_35, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_14
    scr->slider_14 = lv_slider_create(scr->container_24);
    lv_slider_set_range(scr->slider_14, -180, 180);
    lv_slider_set_value(scr->slider_14, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_14, 32, 155);
    lv_obj_set_size(scr->slider_14, 260, 13);

    // Init scr->container_25
    scr->container_25 = lv_obj_create(pose_mode_menu_6_page_5);
    lv_obj_set_pos(scr->container_25, 5, 0);
    lv_obj_set_size(scr->container_25, 319, 184);
    lv_obj_set_scrollbar_mode(scr->container_25, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_25
    lv_obj_set_style_bg_color(scr->container_25, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->container_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->textarea_34
    scr->textarea_34 = lv_textarea_create(scr->container_25);
    lv_textarea_set_one_line(scr->textarea_34, false);
    lv_textarea_set_text(scr->textarea_34, "Pitch limit:\n-180°  to 180°\nReset:\n90°");
    lv_textarea_set_placeholder_text(scr->textarea_34, "");
    lv_obj_set_pos(scr->textarea_34, 14, 18);
    lv_obj_set_size(scr->textarea_34, 130, 105);

    // Set style of scr->textarea_34
    lv_obj_set_style_text_font(scr->textarea_34, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_36
    scr->spinbox_36 = lv_spinbox_create(scr->container_25);

    lv_spinbox_set_range(scr->spinbox_36, -180, 180);
    lv_spinbox_set_step(scr->spinbox_36, 1);
    lv_spinbox_set_digit_format(scr->spinbox_36, 4, 3);
    lv_obj_set_pos(scr->spinbox_36, 203, 65);
    lv_obj_set_size(scr->spinbox_36, 72, 40);

    scr->spinbox_36_left_btn = lv_btn_create(scr->container_25);
    lv_obj_set_size(scr->spinbox_36_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_36_left_btn, scr->spinbox_36, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_36_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_36_left_btn, pose_mode_spinbox_36_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_36_right_btn = lv_btn_create(scr->container_25);
    lv_obj_set_size(scr->spinbox_36_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_36_right_btn, scr->spinbox_36, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_36_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_36_right_btn, pose_mode_spinbox_36_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_36
    lv_obj_set_style_text_font(scr->spinbox_36, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_36, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_36, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_36, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_15
    scr->slider_15 = lv_slider_create(scr->container_25);
    lv_slider_set_range(scr->slider_15, -180, 180);
    lv_slider_set_value(scr->slider_15, 90, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_15, 32, 155);
    lv_obj_set_size(scr->slider_15, 260, 13);

    // Init scr->container_26
    scr->container_26 = lv_obj_create(pose_mode_menu_6_page_6);
    lv_obj_set_pos(scr->container_26, 5, 0);
    lv_obj_set_size(scr->container_26, 319, 184);
    lv_obj_set_scrollbar_mode(scr->container_26, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_26
    lv_obj_set_style_bg_color(scr->container_26, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->container_26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->textarea_35
    scr->textarea_35 = lv_textarea_create(scr->container_26);
    lv_textarea_set_one_line(scr->textarea_35, false);
    lv_textarea_set_text(scr->textarea_35, "Yaw limit:\n-180°  to 180°\nReset:\n180°");
    lv_textarea_set_placeholder_text(scr->textarea_35, "");
    lv_obj_set_pos(scr->textarea_35, 14, 18);
    lv_obj_set_size(scr->textarea_35, 130, 105);

    // Set style of scr->textarea_35
    lv_obj_set_style_text_font(scr->textarea_35, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_37
    scr->spinbox_37 = lv_spinbox_create(scr->container_26);

    lv_spinbox_set_range(scr->spinbox_37, -180, 180);
    lv_spinbox_set_step(scr->spinbox_37, 1);
    lv_spinbox_set_digit_format(scr->spinbox_37, 4, 3);
    lv_obj_set_pos(scr->spinbox_37, 203, 65);
    lv_obj_set_size(scr->spinbox_37, 72, 40);

    scr->spinbox_37_left_btn = lv_btn_create(scr->container_26);
    lv_obj_set_size(scr->spinbox_37_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_37_left_btn, scr->spinbox_37, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_37_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_37_left_btn, pose_mode_spinbox_37_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_37_right_btn = lv_btn_create(scr->container_26);
    lv_obj_set_size(scr->spinbox_37_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_37_right_btn, scr->spinbox_37, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_37_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_37_right_btn, pose_mode_spinbox_37_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_37
    lv_obj_set_style_text_font(scr->spinbox_37, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_37, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_37, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_37, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_16
    scr->slider_16 = lv_slider_create(scr->container_26);
    lv_slider_set_range(scr->slider_16, -180, 180);
    lv_slider_set_value(scr->slider_16, 180, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_16, 32, 155);
    lv_obj_set_size(scr->slider_16, 260, 13);

    // Init scr->pos_run
    scr->pos_run = lv_btn_create(scr->obj);
    lv_obj_t *pos_run_label = lv_label_create(scr->pos_run);
    lv_label_set_text(pos_run_label, "Run");
    lv_obj_align(pos_run_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->pos_run, 350, 228);
    lv_obj_set_size(scr->pos_run, 54, 35);
    lv_obj_add_flag(scr->pos_run, LV_OBJ_FLAG_FLOATING);

    // Set style of scr->pos_run
    lv_obj_set_style_text_font(scr->pos_run, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->pos_run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->pos_run, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->pos_run, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->pos_reset
    scr->pos_reset = lv_btn_create(scr->obj);
    lv_obj_t *pos_reset_label = lv_label_create(scr->pos_reset);
    lv_label_set_text(pos_reset_label, "Reset");
    lv_obj_align(pos_reset_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->pos_reset, 418, 228);
    lv_obj_set_size(scr->pos_reset, 54, 35);
    lv_obj_add_flag(scr->pos_reset, LV_OBJ_FLAG_FLOATING);

    // Set style of scr->pos_reset
    lv_obj_set_style_text_font(scr->pos_reset, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->pos_reset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->pos_reset, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->pos_reset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}
