/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

static void robot_home_pose_mode_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create pose_mode
        pose_mode_create(&ui_manager);
        // load pose_mode
        lv_scr_load_anim(pose_mode_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, true);
    }
}

static void robot_home_angle_mode_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create angle_mode
        angle_mode_create(&ui_manager);
        // load angle_mode
        lv_scr_load_anim(angle_mode_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, true);
    }
}

static void robot_home_arm_information_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create arm_information
        arm_information_create(&ui_manager);
        // load arm_information
        lv_scr_load_anim(arm_information_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, true);
    }
}

static void robot_home_trajectory_planning_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create trajectory_planning
        trajectory_planning_create(&ui_manager);
        // load trajectory_planning
        lv_scr_load_anim(trajectory_planning_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, true);
    }
}

static void robot_home_About_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create About
        About_create(&ui_manager);
        // load About
        lv_scr_load_anim(About_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, true);
    }
}

static void robot_home_advanced_settings_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create advanced_settings
        advanced_settings_create(&ui_manager);
        // load advanced_settings
        lv_scr_load_anim(advanced_settings_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, true);
    }
}

static void robot_home_back2hello_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create robot_hello
        robot_hello_create(&ui_manager);
        // load robot_hello
        lv_scr_load_anim(robot_hello_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, true);
    }
}


void robot_home_create(ui_manager_t *ui)
{
    robot_home_t *scr = robot_home_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_AUTO);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x003a57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->menu
    scr->menu = lv_tileview_create(scr->obj);
    lv_obj_t *robot_home_menu_tile_1 = lv_tileview_add_tile(scr->menu, 0, 0, LV_DIR_ALL);
    lv_obj_t *robot_home_menu_tile_2 = lv_tileview_add_tile(scr->menu, 1, 0, LV_DIR_ALL);
    lv_obj_t *robot_home_menu_tile_3 = lv_tileview_add_tile(scr->menu, 2, 0, LV_DIR_ALL);
    lv_obj_set_pos(scr->menu, 8, 55);
    lv_obj_set_size(scr->menu, 454, 161);
    lv_obj_set_scrollbar_mode(scr->menu, LV_SCROLLBAR_MODE_ON);

    // Set style of scr->menu
    lv_obj_set_style_bg_opa(scr->menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->pose_mode
    scr->pose_mode = lv_btn_create(robot_home_menu_tile_1);
    lv_obj_t *pose_mode_label = lv_label_create(scr->pose_mode);
    lv_label_set_text(pose_mode_label, "Pose mode");
    lv_obj_align(pose_mode_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->pose_mode, 250, 30);
    lv_obj_set_size(scr->pose_mode, 128, 80);

    // Set style of scr->pose_mode
    lv_obj_set_style_text_font(scr->pose_mode, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->pose_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->pose_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->pose_mode
    lv_obj_add_event_cb(scr->pose_mode, robot_home_pose_mode_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->angle_mode
    scr->angle_mode = lv_btn_create(robot_home_menu_tile_1);
    lv_obj_t *angle_mode_label = lv_label_create(scr->angle_mode);
    lv_label_set_text(angle_mode_label, "Angle mode");
    lv_obj_align(angle_mode_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->angle_mode, 80, 30);
    lv_obj_set_size(scr->angle_mode, 128, 80);

    // Set style of scr->angle_mode
    lv_obj_set_style_text_font(scr->angle_mode, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->angle_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->angle_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->angle_mode
    lv_obj_add_event_cb(scr->angle_mode, robot_home_angle_mode_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->arm_information
    scr->arm_information = lv_btn_create(robot_home_menu_tile_2);
    lv_obj_t *arm_information_label = lv_label_create(scr->arm_information);
    lv_label_set_text(arm_information_label, "       Arm\nInformation");
    lv_obj_align(arm_information_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->arm_information, 250, 30);
    lv_obj_set_size(scr->arm_information, 128, 80);

    // Set style of scr->arm_information
    lv_obj_set_style_text_font(scr->arm_information, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->arm_information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->arm_information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->arm_information
    lv_obj_add_event_cb(scr->arm_information, robot_home_arm_information_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->trajectory_planning
    scr->trajectory_planning = lv_btn_create(robot_home_menu_tile_2);
    lv_obj_t *trajectory_planning_label = lv_label_create(scr->trajectory_planning);
    lv_label_set_text(trajectory_planning_label, "Trajectory\n Planning");
    lv_obj_align(trajectory_planning_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->trajectory_planning, 80, 30);
    lv_obj_set_size(scr->trajectory_planning, 128, 80);

    // Set style of scr->trajectory_planning
    lv_obj_set_style_text_font(scr->trajectory_planning, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->trajectory_planning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->trajectory_planning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->trajectory_planning
    lv_obj_add_event_cb(scr->trajectory_planning, robot_home_trajectory_planning_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->About
    scr->About = lv_btn_create(robot_home_menu_tile_3);
    lv_obj_t *About_label = lv_label_create(scr->About);
    lv_label_set_text(About_label, "About");
    lv_obj_align(About_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->About, 250, 30);
    lv_obj_set_size(scr->About, 128, 80);

    // Set style of scr->About
    lv_obj_set_style_text_font(scr->About, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->About
    lv_obj_add_event_cb(scr->About, robot_home_About_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->advanced_settings
    scr->advanced_settings = lv_btn_create(robot_home_menu_tile_3);
    lv_obj_t *advanced_settings_label = lv_label_create(scr->advanced_settings);
    lv_label_set_text(advanced_settings_label, "Advanced \n  Settings");
    lv_obj_align(advanced_settings_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->advanced_settings, 80, 30);
    lv_obj_set_size(scr->advanced_settings, 128, 80);

    // Set style of scr->advanced_settings
    lv_obj_set_style_text_font(scr->advanced_settings, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->advanced_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->advanced_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->advanced_settings
    lv_obj_add_event_cb(scr->advanced_settings, robot_home_advanced_settings_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->Axis_Robot_Home
    scr->Axis_Robot_Home = lv_textarea_create(scr->obj);
    lv_textarea_set_one_line(scr->Axis_Robot_Home, true);
    lv_textarea_set_text(scr->Axis_Robot_Home, "Axis_Robot Home");
    lv_textarea_set_placeholder_text(scr->Axis_Robot_Home, "");
    lv_obj_set_pos(scr->Axis_Robot_Home, 110, 9);
    lv_obj_set_size(scr->Axis_Robot_Home, 260, 50);

    // Set style of scr->Axis_Robot_Home
    lv_obj_set_style_bg_opa(scr->Axis_Robot_Home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->Axis_Robot_Home, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->Axis_Robot_Home, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->Axis_Robot_Home, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->Axis_Robot_Home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->back2hello
    scr->back2hello = lv_btn_create(scr->obj);
    lv_obj_t *back2hello_label = lv_label_create(scr->back2hello);
    lv_label_set_text(back2hello_label, "back");
    lv_obj_align(back2hello_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->back2hello, 6, 228);
    lv_obj_set_size(scr->back2hello, 54, 35);
    lv_obj_add_flag(scr->back2hello, LV_OBJ_FLAG_FLOATING);

    // Set style of scr->back2hello
    lv_obj_set_style_text_font(scr->back2hello, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->back2hello, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->back2hello, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->back2hello, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->back2hello
    lv_obj_add_event_cb(scr->back2hello, robot_home_back2hello_clicked, LV_EVENT_CLICKED, NULL);


}
