/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_16;
lv_font_t *fs_montserratmedium_15;
lv_font_t *fs_montserratmedium_14;
lv_font_t *fs_montserratmedium_20;

void ui_init(void)
{
    fs_montserratmedium_16 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 16);
    fs_montserratmedium_15 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 15);
    fs_montserratmedium_14 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 14);
    fs_montserratmedium_20 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 20);
    if (!fs_montserratmedium_16) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_16");
    	return;
    }
    if (!fs_montserratmedium_15) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_15");
    	return;
    }
    if (!fs_montserratmedium_14) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_14");
    	return;
    }
    if (!fs_montserratmedium_20) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_20");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    robot_hello_create(&ui_manager);
    lv_scr_load(robot_hello_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
