/*
 * Copyright (C) 2024 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.0.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_AUTO);

    // Init scr->switch_1
    scr->switch_1 = lv_switch_create(scr->obj);
    lv_obj_set_pos(scr->switch_1, 393, 31);
    lv_obj_set_size(scr->switch_1, 50, 26);

    // Set style of scr->switch_1
    lv_obj_set_style_radius(scr->switch_1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->led_1
    scr->led_1 = lv_led_create(scr->obj);
    lv_led_set_color(scr->led_1, lv_color_hex(0x2196f3));
    lv_led_set_brightness(scr->led_1, 255);
    lv_obj_set_pos(scr->led_1, 16, 64);
    lv_obj_set_size(scr->led_1, 50, 50);

    // Init scr->animImg_1
    scr->animImg_1 = lv_animimg_create(scr->obj);
    static const char *animImg_1_imgs[1] = {
        LVGL_IMAGE_PATH(goodson_172x230.jpg),
    };
    lv_animimg_set_src(scr->animImg_1, (const void **)animImg_1_imgs, 1);
    lv_animimg_set_duration(scr->animImg_1, 1000);
    lv_animimg_set_repeat_count(scr->animImg_1, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(scr->animImg_1);
    lv_obj_set_pos(scr->animImg_1, 302, 8);
    lv_obj_set_size(scr->animImg_1, 172, 230);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "Button");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 13, 199);
    lv_obj_set_size(scr->button_1, 87, 43);

    // Set style of scr->button_1
    lv_obj_set_style_text_font(scr->button_1, montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_1
    scr->arc_1 = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->arc_1, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_1, 0, 100);
    lv_arc_set_bg_angles(scr->arc_1, 135, 45);
    lv_arc_set_angles(scr->arc_1, 135, 270);
    lv_arc_set_rotation(scr->arc_1, 0);
    lv_obj_set_pos(scr->arc_1, 107, 65);
    lv_obj_set_size(scr->arc_1, 130, 130);

    // Init scr->switch_2
    scr->switch_2 = lv_switch_create(scr->obj);
    lv_obj_set_pos(scr->switch_2, 91, 10);
    lv_obj_set_size(scr->switch_2, 77, 36);

    // Set style of scr->switch_2
    lv_obj_set_style_radius(scr->switch_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->slider_1
    scr->slider_1 = lv_slider_create(scr->obj);
    lv_slider_set_range(scr->slider_1, 0, 100);
    lv_slider_set_value(scr->slider_1, 50, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_1, 110, 250);
    lv_obj_set_size(scr->slider_1, 260, 13);


}
