/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

static void About_button_8_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create robot_home
        robot_home_create(&ui_manager);
        // load robot_home
        lv_scr_load_anim(robot_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, true);
    }
}


void About_create(ui_manager_t *ui)
{
    About_t *scr = About_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x003a57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_8
    scr->button_8 = lv_btn_create(scr->obj);
    lv_obj_t *button_8_label = lv_label_create(scr->button_8);
    lv_label_set_text(button_8_label, "back");
    lv_obj_align(button_8_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_8, 6, 228);
    lv_obj_set_size(scr->button_8, 54, 35);
    lv_obj_add_flag(scr->button_8, LV_OBJ_FLAG_FLOATING);

    // Set style of scr->button_8
    lv_obj_set_style_text_font(scr->button_8, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->button_8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_8
    lv_obj_add_event_cb(scr->button_8, About_button_8_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->about_txt
    scr->about_txt = lv_textarea_create(scr->obj);
    lv_textarea_set_one_line(scr->about_txt, true);
    lv_textarea_set_text(scr->about_txt, "Axis_Robot About");
    lv_textarea_set_placeholder_text(scr->about_txt, "");
    lv_obj_set_pos(scr->about_txt, 71, -8);
    lv_obj_set_size(scr->about_txt, 337, 50);

    // Set style of scr->about_txt
    lv_obj_set_style_bg_opa(scr->about_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->about_txt, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->about_txt, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->about_txt, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->about_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->tileview_3
    scr->tileview_3 = lv_tileview_create(scr->obj);
    lv_obj_t *About_tileview_3_tile_1 = lv_tileview_add_tile(scr->tileview_3, 0, 0, LV_DIR_ALL);
    lv_obj_t *About_tileview_3_tile_2 = lv_tileview_add_tile(scr->tileview_3, 0, 1, LV_DIR_ALL);
    lv_obj_set_pos(scr->tileview_3, 4, 40);
    lv_obj_set_size(scr->tileview_3, 471, 177);
    lv_obj_set_scrollbar_mode(scr->tileview_3, LV_SCROLLBAR_MODE_ON);

    // Init scr->textarea_27
    scr->textarea_27 = lv_textarea_create(About_tileview_3_tile_1);
    lv_textarea_set_one_line(scr->textarea_27, false);
    lv_textarea_set_text(scr->textarea_27, "NJTECH Undergraduate Graduation Project\nDesign:Axis_Robot\nAuthor:aiyilin\nDate:2025.05");
    lv_textarea_set_placeholder_text(scr->textarea_27, "");
    lv_obj_set_pos(scr->textarea_27, 20, 18);
    lv_obj_set_size(scr->textarea_27, 388, 137);

    // Set style of scr->textarea_27
    lv_obj_set_style_text_font(scr->textarea_27, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->textarea_28
    scr->textarea_28 = lv_textarea_create(About_tileview_3_tile_2);
    lv_textarea_set_one_line(scr->textarea_28, false);
    lv_textarea_set_text(scr->textarea_28, "scan QR-Code for more detail");
    lv_textarea_set_placeholder_text(scr->textarea_28, "");
    lv_obj_set_pos(scr->textarea_28, 29, 49);
    lv_obj_set_size(scr->textarea_28, 124, 81);

    // Set style of scr->textarea_28
    lv_obj_set_style_text_font(scr->textarea_28, fs_montserratmedium_15, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1
    scr->image_1 = lv_img_create(About_tileview_3_tile_2);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(aiyilin_qr_code.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_style_img_opa(scr->image_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_1, 185, 37);


}
