/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

static void advanced_settings_button_30_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create robot_home
        robot_home_create(&ui_manager);
        // load robot_home
        lv_scr_load_anim(robot_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, true);
    }
}


void advanced_settings_create(ui_manager_t *ui)
{
    advanced_settings_t *scr = advanced_settings_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x003a57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_30
    scr->button_30 = lv_btn_create(scr->obj);
    lv_obj_t *button_30_label = lv_label_create(scr->button_30);
    lv_label_set_text(button_30_label, "back");
    lv_obj_align(button_30_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_30, 6, 228);
    lv_obj_set_size(scr->button_30, 54, 35);
    lv_obj_add_flag(scr->button_30, LV_OBJ_FLAG_FLOATING);

    // Set style of scr->button_30
    lv_obj_set_style_text_font(scr->button_30, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->button_30, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_30
    lv_obj_add_event_cb(scr->button_30, advanced_settings_button_30_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->adv_setting_txt
    scr->adv_setting_txt = lv_textarea_create(scr->obj);
    lv_textarea_set_one_line(scr->adv_setting_txt, true);
    lv_textarea_set_text(scr->adv_setting_txt, "Axis_Robot Advanced Settings");
    lv_textarea_set_placeholder_text(scr->adv_setting_txt, "");
    lv_obj_set_pos(scr->adv_setting_txt, 57, -8);
    lv_obj_set_size(scr->adv_setting_txt, 365, 50);

    // Set style of scr->adv_setting_txt
    lv_obj_set_style_bg_opa(scr->adv_setting_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->adv_setting_txt, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->adv_setting_txt, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->adv_setting_txt, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->adv_setting_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


}
