/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

static void angle_mode_spinbox_31_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(angle_mode_get(&ui_manager)->spinbox_31);
    }
}

static void angle_mode_spinbox_31_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(angle_mode_get(&ui_manager)->spinbox_31);
    }
}

static void angle_mode_spinbox_30_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(angle_mode_get(&ui_manager)->spinbox_30);
    }
}

static void angle_mode_spinbox_30_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(angle_mode_get(&ui_manager)->spinbox_30);
    }
}

static void angle_mode_spinbox_29_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(angle_mode_get(&ui_manager)->spinbox_29);
    }
}

static void angle_mode_spinbox_29_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(angle_mode_get(&ui_manager)->spinbox_29);
    }
}

static void angle_mode_spinbox_28_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(angle_mode_get(&ui_manager)->spinbox_28);
    }
}

static void angle_mode_spinbox_28_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(angle_mode_get(&ui_manager)->spinbox_28);
    }
}

static void angle_mode_spinbox_27_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(angle_mode_get(&ui_manager)->spinbox_27);
    }
}

static void angle_mode_spinbox_27_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(angle_mode_get(&ui_manager)->spinbox_27);
    }
}

static void angle_mode_spinbox_20_left_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(angle_mode_get(&ui_manager)->spinbox_20);
    }
}

static void angle_mode_spinbox_20_right_btn_clicked(lv_event_t * event) {
    lv_event_code_t code = lv_event_get_code(event);
    if (code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(angle_mode_get(&ui_manager)->spinbox_20);
    }
}

static void angle_mode_pos_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create robot_home
        robot_home_create(&ui_manager);
        // load robot_home
        lv_scr_load_anim(robot_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, true);
    }
}


void angle_mode_create(ui_manager_t *ui)
{
    angle_mode_t *scr = angle_mode_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x003a57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->angle_joint_set_menu
    scr->angle_joint_set_menu = lv_menu_create(scr->obj);
    lv_obj_t *angle_mode_angle_joint_set_menu_sidebar = lv_menu_page_create(scr->angle_joint_set_menu, NULL);
    lv_menu_set_sidebar_page(scr->angle_joint_set_menu, angle_mode_angle_joint_set_menu_sidebar);
    lv_obj_t *angle_mode_angle_joint_set_menu_sidebar_header = lv_menu_get_sidebar_header(scr->angle_joint_set_menu);
    lv_obj_add_flag(angle_mode_angle_joint_set_menu_sidebar_header, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t *angle_joint_set_menu_main_header = lv_menu_get_main_header(scr->angle_joint_set_menu);
    lv_obj_add_flag(angle_joint_set_menu_main_header, LV_OBJ_FLAG_HIDDEN);

    lv_obj_t *angle_mode_angle_joint_set_menu_page_1 = lv_menu_page_create(scr->angle_joint_set_menu, NULL);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_1 = lv_menu_cont_create(angle_mode_angle_joint_set_menu_sidebar);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_1_lab = lv_label_create(angle_mode_angle_joint_set_menu_cont_1);
    lv_label_set_text(angle_mode_angle_joint_set_menu_cont_1_lab, "joint-1");
    lv_menu_set_load_page_event(scr->angle_joint_set_menu, angle_mode_angle_joint_set_menu_cont_1, angle_mode_angle_joint_set_menu_page_1);

    lv_obj_t *angle_mode_angle_joint_set_menu_page_2 = lv_menu_page_create(scr->angle_joint_set_menu, NULL);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_2 = lv_menu_cont_create(angle_mode_angle_joint_set_menu_sidebar);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_2_lab = lv_label_create(angle_mode_angle_joint_set_menu_cont_2);
    lv_label_set_text(angle_mode_angle_joint_set_menu_cont_2_lab, "joint-2");
    lv_menu_set_load_page_event(scr->angle_joint_set_menu, angle_mode_angle_joint_set_menu_cont_2, angle_mode_angle_joint_set_menu_page_2);

    lv_obj_t *angle_mode_angle_joint_set_menu_page_3 = lv_menu_page_create(scr->angle_joint_set_menu, NULL);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_3 = lv_menu_cont_create(angle_mode_angle_joint_set_menu_sidebar);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_3_lab = lv_label_create(angle_mode_angle_joint_set_menu_cont_3);
    lv_label_set_text(angle_mode_angle_joint_set_menu_cont_3_lab, "joint-3");
    lv_menu_set_load_page_event(scr->angle_joint_set_menu, angle_mode_angle_joint_set_menu_cont_3, angle_mode_angle_joint_set_menu_page_3);

    lv_obj_t *angle_mode_angle_joint_set_menu_page_4 = lv_menu_page_create(scr->angle_joint_set_menu, NULL);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_4 = lv_menu_cont_create(angle_mode_angle_joint_set_menu_sidebar);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_4_lab = lv_label_create(angle_mode_angle_joint_set_menu_cont_4);
    lv_label_set_text(angle_mode_angle_joint_set_menu_cont_4_lab, "joint-4");
    lv_menu_set_load_page_event(scr->angle_joint_set_menu, angle_mode_angle_joint_set_menu_cont_4, angle_mode_angle_joint_set_menu_page_4);

    lv_obj_t *angle_mode_angle_joint_set_menu_page_5 = lv_menu_page_create(scr->angle_joint_set_menu, NULL);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_5 = lv_menu_cont_create(angle_mode_angle_joint_set_menu_sidebar);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_5_lab = lv_label_create(angle_mode_angle_joint_set_menu_cont_5);
    lv_label_set_text(angle_mode_angle_joint_set_menu_cont_5_lab, "joint-5");
    lv_menu_set_load_page_event(scr->angle_joint_set_menu, angle_mode_angle_joint_set_menu_cont_5, angle_mode_angle_joint_set_menu_page_5);

    lv_obj_t *angle_mode_angle_joint_set_menu_page_6 = lv_menu_page_create(scr->angle_joint_set_menu, NULL);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_6 = lv_menu_cont_create(angle_mode_angle_joint_set_menu_sidebar);
    lv_obj_t *angle_mode_angle_joint_set_menu_cont_6_lab = lv_label_create(angle_mode_angle_joint_set_menu_cont_6);
    lv_label_set_text(angle_mode_angle_joint_set_menu_cont_6_lab, "joint-6");
    lv_menu_set_load_page_event(scr->angle_joint_set_menu, angle_mode_angle_joint_set_menu_cont_6, angle_mode_angle_joint_set_menu_page_6);

#if LVGL_VERSION_MAJOR == 8
    lv_event_send(angle_mode_angle_joint_set_menu_cont_1, LV_EVENT_CLICKED, NULL);
#else
    lv_obj_send_event(angle_mode_angle_joint_set_menu_cont_1, LV_EVENT_CLICKED, NULL);
#endif
    lv_obj_set_pos(scr->angle_joint_set_menu, 5, 35);
    lv_obj_set_size(scr->angle_joint_set_menu, 471, 189);

    // Set style of scr->angle_joint_set_menu
    lv_obj_set_style_bg_color(scr->angle_joint_set_menu, lv_color_hex(0xe6e6e6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->angle_joint_set_menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(angle_mode_angle_joint_set_menu_cont_1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(angle_mode_angle_joint_set_menu_cont_1, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(angle_mode_angle_joint_set_menu_cont_2, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(angle_mode_angle_joint_set_menu_cont_2, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(angle_mode_angle_joint_set_menu_cont_3, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(angle_mode_angle_joint_set_menu_cont_3, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(angle_mode_angle_joint_set_menu_cont_4, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(angle_mode_angle_joint_set_menu_cont_4, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(angle_mode_angle_joint_set_menu_cont_5, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(angle_mode_angle_joint_set_menu_cont_5, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(angle_mode_angle_joint_set_menu_cont_6, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(angle_mode_angle_joint_set_menu_cont_6, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_CHECKED);

    // Init scr->angle_j1_contain
    scr->angle_j1_contain = lv_obj_create(angle_mode_angle_joint_set_menu_page_1);
    lv_obj_set_pos(scr->angle_j1_contain, 5, 0);
    lv_obj_set_size(scr->angle_j1_contain, 319, 184);
    lv_obj_set_scrollbar_mode(scr->angle_j1_contain, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->angle_j1_contain
    lv_obj_set_style_bg_color(scr->angle_j1_contain, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->angle_j1_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->angle_j1_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->angle_j1_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->angle_j1_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->angle_j1_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->angle_j1_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->angle_j1_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->angle_j1_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->angle_j1_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->J1_TXT
    scr->J1_TXT = lv_textarea_create(scr->angle_j1_contain);
    lv_textarea_set_one_line(scr->J1_TXT, false);
    lv_textarea_set_text(scr->J1_TXT, "J1 limit:\n-180°  to 180°\nReset:\n0°");
    lv_textarea_set_placeholder_text(scr->J1_TXT, "");
    lv_obj_set_pos(scr->J1_TXT, 14, 18);
    lv_obj_set_size(scr->J1_TXT, 130, 105);

    // Set style of scr->J1_TXT
    lv_obj_set_style_text_font(scr->J1_TXT, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_31
    scr->spinbox_31 = lv_spinbox_create(scr->angle_j1_contain);

    lv_spinbox_set_range(scr->spinbox_31, -180, 180);
    lv_spinbox_set_step(scr->spinbox_31, 1);
    lv_spinbox_set_digit_format(scr->spinbox_31, 4, 3);
    lv_obj_set_pos(scr->spinbox_31, 203, 65);
    lv_obj_set_size(scr->spinbox_31, 72, 40);

    scr->spinbox_31_left_btn = lv_btn_create(scr->angle_j1_contain);
    lv_obj_set_size(scr->spinbox_31_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_31_left_btn, scr->spinbox_31, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_31_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_31_left_btn, angle_mode_spinbox_31_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_31_right_btn = lv_btn_create(scr->angle_j1_contain);
    lv_obj_set_size(scr->spinbox_31_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_31_right_btn, scr->spinbox_31, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_31_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_31_right_btn, angle_mode_spinbox_31_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_31
    lv_obj_set_style_text_font(scr->spinbox_31, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_31, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_31, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_31, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_10
    scr->slider_10 = lv_slider_create(scr->angle_j1_contain);
    lv_slider_set_range(scr->slider_10, -180, 180);
    lv_slider_set_value(scr->slider_10, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_10, 32, 155);
    lv_obj_set_size(scr->slider_10, 260, 13);

    // Init scr->angle_j2_contain
    scr->angle_j2_contain = lv_obj_create(angle_mode_angle_joint_set_menu_page_2);
    lv_obj_set_pos(scr->angle_j2_contain, 5, 0);
    lv_obj_set_size(scr->angle_j2_contain, 319, 184);
    lv_obj_set_scrollbar_mode(scr->angle_j2_contain, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->angle_j2_contain
    lv_obj_set_style_bg_color(scr->angle_j2_contain, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->angle_j2_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->angle_j2_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->angle_j2_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->angle_j2_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->angle_j2_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->angle_j2_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->angle_j2_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->angle_j2_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->angle_j2_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->J2_TXT
    scr->J2_TXT = lv_textarea_create(scr->angle_j2_contain);
    lv_textarea_set_one_line(scr->J2_TXT, false);
    lv_textarea_set_text(scr->J2_TXT, "J2 limit:\n-180°  to 180°\nReset:\n0°");
    lv_textarea_set_placeholder_text(scr->J2_TXT, "");
    lv_obj_set_pos(scr->J2_TXT, 14, 18);
    lv_obj_set_size(scr->J2_TXT, 130, 105);

    // Set style of scr->J2_TXT
    lv_obj_set_style_text_font(scr->J2_TXT, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_30
    scr->spinbox_30 = lv_spinbox_create(scr->angle_j2_contain);

    lv_spinbox_set_range(scr->spinbox_30, -180, 180);
    lv_spinbox_set_step(scr->spinbox_30, 1);
    lv_spinbox_set_digit_format(scr->spinbox_30, 4, 3);
    lv_obj_set_pos(scr->spinbox_30, 203, 65);
    lv_obj_set_size(scr->spinbox_30, 72, 40);

    scr->spinbox_30_left_btn = lv_btn_create(scr->angle_j2_contain);
    lv_obj_set_size(scr->spinbox_30_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_30_left_btn, scr->spinbox_30, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_30_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_30_left_btn, angle_mode_spinbox_30_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_30_right_btn = lv_btn_create(scr->angle_j2_contain);
    lv_obj_set_size(scr->spinbox_30_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_30_right_btn, scr->spinbox_30, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_30_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_30_right_btn, angle_mode_spinbox_30_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_30
    lv_obj_set_style_text_font(scr->spinbox_30, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_30, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_30, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_30, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_9
    scr->slider_9 = lv_slider_create(scr->angle_j2_contain);
    lv_slider_set_range(scr->slider_9, -180, 180);
    lv_slider_set_value(scr->slider_9, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_9, 32, 155);
    lv_obj_set_size(scr->slider_9, 260, 13);

    // Init scr->angle_j3_contain
    scr->angle_j3_contain = lv_obj_create(angle_mode_angle_joint_set_menu_page_3);
    lv_obj_set_pos(scr->angle_j3_contain, 5, 0);
    lv_obj_set_size(scr->angle_j3_contain, 319, 184);
    lv_obj_set_scrollbar_mode(scr->angle_j3_contain, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->angle_j3_contain
    lv_obj_set_style_bg_color(scr->angle_j3_contain, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->angle_j3_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->angle_j3_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->angle_j3_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->angle_j3_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->angle_j3_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->angle_j3_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->angle_j3_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->angle_j3_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->angle_j3_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->J3_TXT
    scr->J3_TXT = lv_textarea_create(scr->angle_j3_contain);
    lv_textarea_set_one_line(scr->J3_TXT, false);
    lv_textarea_set_text(scr->J3_TXT, "J3 limit:\n-180°  to 180°\nReset:\n0°");
    lv_textarea_set_placeholder_text(scr->J3_TXT, "");
    lv_obj_set_pos(scr->J3_TXT, 14, 18);
    lv_obj_set_size(scr->J3_TXT, 130, 105);

    // Set style of scr->J3_TXT
    lv_obj_set_style_text_font(scr->J3_TXT, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_29
    scr->spinbox_29 = lv_spinbox_create(scr->angle_j3_contain);

    lv_spinbox_set_range(scr->spinbox_29, -180, 180);
    lv_spinbox_set_step(scr->spinbox_29, 1);
    lv_spinbox_set_digit_format(scr->spinbox_29, 4, 3);
    lv_obj_set_pos(scr->spinbox_29, 203, 65);
    lv_obj_set_size(scr->spinbox_29, 72, 40);

    scr->spinbox_29_left_btn = lv_btn_create(scr->angle_j3_contain);
    lv_obj_set_size(scr->spinbox_29_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_29_left_btn, scr->spinbox_29, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_29_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_29_left_btn, angle_mode_spinbox_29_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_29_right_btn = lv_btn_create(scr->angle_j3_contain);
    lv_obj_set_size(scr->spinbox_29_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_29_right_btn, scr->spinbox_29, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_29_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_29_right_btn, angle_mode_spinbox_29_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_29
    lv_obj_set_style_text_font(scr->spinbox_29, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_29, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_29, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_29, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_8
    scr->slider_8 = lv_slider_create(scr->angle_j3_contain);
    lv_slider_set_range(scr->slider_8, -180, 180);
    lv_slider_set_value(scr->slider_8, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_8, 32, 155);
    lv_obj_set_size(scr->slider_8, 260, 13);

    // Init scr->angle_j4_contain
    scr->angle_j4_contain = lv_obj_create(angle_mode_angle_joint_set_menu_page_4);
    lv_obj_set_pos(scr->angle_j4_contain, 5, 0);
    lv_obj_set_size(scr->angle_j4_contain, 319, 184);
    lv_obj_set_scrollbar_mode(scr->angle_j4_contain, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->angle_j4_contain
    lv_obj_set_style_bg_color(scr->angle_j4_contain, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->angle_j4_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->angle_j4_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->angle_j4_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->angle_j4_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->angle_j4_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->angle_j4_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->angle_j4_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->angle_j4_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->angle_j4_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->J4_TXT
    scr->J4_TXT = lv_textarea_create(scr->angle_j4_contain);
    lv_textarea_set_one_line(scr->J4_TXT, false);
    lv_textarea_set_text(scr->J4_TXT, "J4 limit:\n-180°  to 180°\nReset:\n0°");
    lv_textarea_set_placeholder_text(scr->J4_TXT, "");
    lv_obj_set_pos(scr->J4_TXT, 14, 18);
    lv_obj_set_size(scr->J4_TXT, 130, 105);

    // Set style of scr->J4_TXT
    lv_obj_set_style_text_font(scr->J4_TXT, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_28
    scr->spinbox_28 = lv_spinbox_create(scr->angle_j4_contain);

    lv_spinbox_set_range(scr->spinbox_28, -180, 180);
    lv_spinbox_set_step(scr->spinbox_28, 1);
    lv_spinbox_set_digit_format(scr->spinbox_28, 4, 3);
    lv_obj_set_pos(scr->spinbox_28, 203, 65);
    lv_obj_set_size(scr->spinbox_28, 72, 40);

    scr->spinbox_28_left_btn = lv_btn_create(scr->angle_j4_contain);
    lv_obj_set_size(scr->spinbox_28_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_28_left_btn, scr->spinbox_28, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_28_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_28_left_btn, angle_mode_spinbox_28_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_28_right_btn = lv_btn_create(scr->angle_j4_contain);
    lv_obj_set_size(scr->spinbox_28_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_28_right_btn, scr->spinbox_28, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_28_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_28_right_btn, angle_mode_spinbox_28_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_28
    lv_obj_set_style_text_font(scr->spinbox_28, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_28, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_28, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_28, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_7
    scr->slider_7 = lv_slider_create(scr->angle_j4_contain);
    lv_slider_set_range(scr->slider_7, -180, 180);
    lv_slider_set_value(scr->slider_7, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_7, 32, 155);
    lv_obj_set_size(scr->slider_7, 260, 13);

    // Init scr->angle_j5_contain
    scr->angle_j5_contain = lv_obj_create(angle_mode_angle_joint_set_menu_page_5);
    lv_obj_set_pos(scr->angle_j5_contain, 5, 0);
    lv_obj_set_size(scr->angle_j5_contain, 319, 184);
    lv_obj_set_scrollbar_mode(scr->angle_j5_contain, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->angle_j5_contain
    lv_obj_set_style_bg_color(scr->angle_j5_contain, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->angle_j5_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->angle_j5_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->angle_j5_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->angle_j5_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->angle_j5_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->angle_j5_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->angle_j5_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->angle_j5_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->angle_j5_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->J5_TXT
    scr->J5_TXT = lv_textarea_create(scr->angle_j5_contain);
    lv_textarea_set_one_line(scr->J5_TXT, false);
    lv_textarea_set_text(scr->J5_TXT, "J5 limit:\n-180°  to 180°\nReset:\n0°");
    lv_textarea_set_placeholder_text(scr->J5_TXT, "");
    lv_obj_set_pos(scr->J5_TXT, 14, 18);
    lv_obj_set_size(scr->J5_TXT, 130, 105);

    // Set style of scr->J5_TXT
    lv_obj_set_style_text_font(scr->J5_TXT, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_27
    scr->spinbox_27 = lv_spinbox_create(scr->angle_j5_contain);

    lv_spinbox_set_range(scr->spinbox_27, -180, 180);
    lv_spinbox_set_step(scr->spinbox_27, 1);
    lv_spinbox_set_digit_format(scr->spinbox_27, 4, 3);
    lv_obj_set_pos(scr->spinbox_27, 203, 65);
    lv_obj_set_size(scr->spinbox_27, 72, 40);

    scr->spinbox_27_left_btn = lv_btn_create(scr->angle_j5_contain);
    lv_obj_set_size(scr->spinbox_27_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_27_left_btn, scr->spinbox_27, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_27_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_27_left_btn, angle_mode_spinbox_27_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_27_right_btn = lv_btn_create(scr->angle_j5_contain);
    lv_obj_set_size(scr->spinbox_27_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_27_right_btn, scr->spinbox_27, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_27_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_27_right_btn, angle_mode_spinbox_27_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_27
    lv_obj_set_style_text_font(scr->spinbox_27, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_27, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_27, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_27, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_6
    scr->slider_6 = lv_slider_create(scr->angle_j5_contain);
    lv_slider_set_range(scr->slider_6, -180, 180);
    lv_slider_set_value(scr->slider_6, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_6, 32, 155);
    lv_obj_set_size(scr->slider_6, 260, 13);

    // Init scr->angle_j6_contain
    scr->angle_j6_contain = lv_obj_create(angle_mode_angle_joint_set_menu_page_6);
    lv_obj_set_pos(scr->angle_j6_contain, 5, 0);
    lv_obj_set_size(scr->angle_j6_contain, 319, 184);
    lv_obj_set_scrollbar_mode(scr->angle_j6_contain, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->angle_j6_contain
    lv_obj_set_style_bg_color(scr->angle_j6_contain, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->angle_j6_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->angle_j6_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->angle_j6_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->angle_j6_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->angle_j6_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->angle_j6_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->angle_j6_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->angle_j6_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->angle_j6_contain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->J6_TXT
    scr->J6_TXT = lv_textarea_create(scr->angle_j6_contain);
    lv_textarea_set_one_line(scr->J6_TXT, false);
    lv_textarea_set_text(scr->J6_TXT, "J6 limit:\n-180°  to 180°\nReset:\n0°");
    lv_textarea_set_placeholder_text(scr->J6_TXT, "");
    lv_obj_set_pos(scr->J6_TXT, 14, 18);
    lv_obj_set_size(scr->J6_TXT, 130, 105);

    // Set style of scr->J6_TXT
    lv_obj_set_style_text_font(scr->J6_TXT, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->spinbox_20
    scr->spinbox_20 = lv_spinbox_create(scr->angle_j6_contain);

    lv_spinbox_set_range(scr->spinbox_20, -180, 180);
    lv_spinbox_set_step(scr->spinbox_20, 1);
    lv_spinbox_set_digit_format(scr->spinbox_20, 4, 3);
    lv_obj_set_pos(scr->spinbox_20, 203, 65);
    lv_obj_set_size(scr->spinbox_20, 72, 40);

    scr->spinbox_20_left_btn = lv_btn_create(scr->angle_j6_contain);
    lv_obj_set_size(scr->spinbox_20_left_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_20_left_btn, scr->spinbox_20, LV_ALIGN_OUT_LEFT_MID, -5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_20_left_btn, LV_SYMBOL_MINUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_20_left_btn, angle_mode_spinbox_20_left_btn_clicked, LV_EVENT_ALL, NULL);

    scr->spinbox_20_right_btn = lv_btn_create(scr->angle_j6_contain);
    lv_obj_set_size(scr->spinbox_20_right_btn, 40, 40);
    lv_obj_align_to(scr->spinbox_20_right_btn, scr->spinbox_20, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    lv_obj_set_style_bg_img_src(scr->spinbox_20_right_btn, LV_SYMBOL_PLUS, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(scr->spinbox_20_right_btn, angle_mode_spinbox_20_right_btn_clicked, LV_EVENT_ALL, NULL);

    // Set style of scr->spinbox_20
    lv_obj_set_style_text_font(scr->spinbox_20, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->spinbox_20, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->spinbox_20, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->spinbox_20, fs_montserratmedium_16, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Init scr->slider_5
    scr->slider_5 = lv_slider_create(scr->angle_j6_contain);
    lv_slider_set_range(scr->slider_5, -180, 180);
    lv_slider_set_value(scr->slider_5, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_5, 32, 155);
    lv_obj_set_size(scr->slider_5, 260, 13);

    // Init scr->angle_set_mode_TXT
    scr->angle_set_mode_TXT = lv_textarea_create(scr->obj);
    lv_textarea_set_one_line(scr->angle_set_mode_TXT, true);
    lv_textarea_set_text(scr->angle_set_mode_TXT, "Axis_Robot Angle Set mode");
    lv_textarea_set_placeholder_text(scr->angle_set_mode_TXT, "");
    lv_obj_set_pos(scr->angle_set_mode_TXT, 71, -8);
    lv_obj_set_size(scr->angle_set_mode_TXT, 337, 57);

    // Set style of scr->angle_set_mode_TXT
    lv_obj_set_style_bg_opa(scr->angle_set_mode_TXT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->angle_set_mode_TXT, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->angle_set_mode_TXT, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->angle_set_mode_TXT, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->angle_set_mode_TXT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->pos_back
    scr->pos_back = lv_btn_create(scr->obj);
    lv_obj_t *pos_back_label = lv_label_create(scr->pos_back);
    lv_label_set_text(pos_back_label, "back");
    lv_obj_align(pos_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->pos_back, 6, 228);
    lv_obj_set_size(scr->pos_back, 54, 35);
    lv_obj_add_flag(scr->pos_back, LV_OBJ_FLAG_FLOATING);

    // Set style of scr->pos_back
    lv_obj_set_style_text_font(scr->pos_back, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->pos_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->pos_back, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->pos_back, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->pos_back
    lv_obj_add_event_cb(scr->pos_back, angle_mode_pos_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->angle_Reset
    scr->angle_Reset = lv_btn_create(scr->obj);
    lv_obj_t *angle_Reset_label = lv_label_create(scr->angle_Reset);
    lv_label_set_text(angle_Reset_label, "Reset");
    lv_obj_align(angle_Reset_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->angle_Reset, 418, 228);
    lv_obj_set_size(scr->angle_Reset, 54, 35);
    lv_obj_add_flag(scr->angle_Reset, LV_OBJ_FLAG_FLOATING);

    // Set style of scr->angle_Reset
    lv_obj_set_style_text_font(scr->angle_Reset, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->angle_Reset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->angle_Reset, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->angle_Reset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->angle_run
    scr->angle_run = lv_btn_create(scr->obj);
    lv_obj_t *angle_run_label = lv_label_create(scr->angle_run);
    lv_label_set_text(angle_run_label, "Run");
    lv_obj_align(angle_run_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->angle_run, 350, 228);
    lv_obj_set_size(scr->angle_run, 54, 35);
    lv_obj_add_flag(scr->angle_run, LV_OBJ_FLAG_FLOATING);

    // Set style of scr->angle_run
    lv_obj_set_style_text_font(scr->angle_run, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->angle_run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->angle_run, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->angle_run, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}
