/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

static void robot_hello_go2menu_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create robot_home
        robot_home_create(&ui_manager);
        // load robot_home
        lv_scr_load_anim(robot_home_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, true);
    }
}


void robot_hello_create(ui_manager_t *ui)
{
    robot_hello_t *scr = robot_hello_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_AUTO);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x003a57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->go2menu
    scr->go2menu = lv_btn_create(scr->obj);
    lv_obj_t *go2menu_label = lv_label_create(scr->go2menu);
    lv_label_set_text(go2menu_label, "");
    lv_obj_align(go2menu_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->go2menu, 7, 8);
    lv_obj_set_size(scr->go2menu, 465, 255);

    // Set style of scr->go2menu
    lv_obj_set_style_bg_opa(scr->go2menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->go2menu, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->go2menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->go2menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->go2menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->go2menu, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->go2menu
    lv_obj_add_event_cb(scr->go2menu, robot_hello_go2menu_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->textarea_29
    scr->textarea_29 = lv_textarea_create(scr->obj);
    lv_textarea_set_one_line(scr->textarea_29, true);
    lv_textarea_set_text(scr->textarea_29, "press to enter");
    lv_textarea_set_placeholder_text(scr->textarea_29, "");
    lv_obj_set_pos(scr->textarea_29, 110, 237);
    lv_obj_set_size(scr->textarea_29, 262, 26);

    // Set style of scr->textarea_29
    lv_obj_set_style_bg_color(scr->textarea_29, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->textarea_29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->textarea_29, fs_montserratmedium_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->textarea_29, lv_color_hex(0xbfbab3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->textarea_29, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->textarea_29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->textarea_29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->textarea_29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->textarea_29, 56, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->textarea_29, lv_color_hex(0x00aaff), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->textarea_29, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    // Init scr->hello_text
    scr->hello_text = lv_textarea_create(scr->obj);
    lv_textarea_set_one_line(scr->hello_text, true);
    lv_textarea_set_text(scr->hello_text, "Hello Axis_Robot");
    lv_textarea_set_placeholder_text(scr->hello_text, "");
    lv_obj_set_pos(scr->hello_text, 110, 110);
    lv_obj_set_size(scr->hello_text, 260, 50);

    // Set style of scr->hello_text
    lv_obj_set_style_bg_opa(scr->hello_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->hello_text, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hello_text, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->hello_text, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->hello_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


}
