/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"

#define CONN(x, y) x#y

#define LVGL_UI_BUILDER_FONT    LVGL_STORAGE_PATH"/font/"
#define LVGL_UI_BUILDER_IMAGE   "L:"LVGL_STORAGE_PATH"/image/"

#define LVGL_FONT_PATH(y)  CONN(LVGL_UI_BUILDER_FONT,  y)
#define LVGL_IMAGE_PATH(y) CONN(LVGL_UI_BUILDER_IMAGE, y)

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *go2menu;
    lv_obj_t *textarea_29;
    lv_obj_t *hello_text;
} robot_hello_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *menu;
    lv_obj_t *pose_mode;
    lv_obj_t *angle_mode;
    lv_obj_t *arm_information;
    lv_obj_t *trajectory_planning;
    lv_obj_t *About;
    lv_obj_t *advanced_settings;
    lv_obj_t *Axis_Robot_Home;
    lv_obj_t *back2hello;
} robot_home_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *angle_joint_set_menu;
    lv_obj_t *angle_j1_contain;
    lv_obj_t *J1_TXT;
    lv_obj_t *spinbox_31;
    lv_obj_t *spinbox_31_left_btn;
    lv_obj_t *spinbox_31_right_btn;
    lv_obj_t *slider_10;
    lv_obj_t *angle_j2_contain;
    lv_obj_t *J2_TXT;
    lv_obj_t *spinbox_30;
    lv_obj_t *spinbox_30_left_btn;
    lv_obj_t *spinbox_30_right_btn;
    lv_obj_t *slider_9;
    lv_obj_t *angle_j3_contain;
    lv_obj_t *J3_TXT;
    lv_obj_t *spinbox_29;
    lv_obj_t *spinbox_29_left_btn;
    lv_obj_t *spinbox_29_right_btn;
    lv_obj_t *slider_8;
    lv_obj_t *angle_j4_contain;
    lv_obj_t *J4_TXT;
    lv_obj_t *spinbox_28;
    lv_obj_t *spinbox_28_left_btn;
    lv_obj_t *spinbox_28_right_btn;
    lv_obj_t *slider_7;
    lv_obj_t *angle_j5_contain;
    lv_obj_t *J5_TXT;
    lv_obj_t *spinbox_27;
    lv_obj_t *spinbox_27_left_btn;
    lv_obj_t *spinbox_27_right_btn;
    lv_obj_t *slider_6;
    lv_obj_t *angle_j6_contain;
    lv_obj_t *J6_TXT;
    lv_obj_t *spinbox_20;
    lv_obj_t *spinbox_20_left_btn;
    lv_obj_t *spinbox_20_right_btn;
    lv_obj_t *slider_5;
    lv_obj_t *angle_set_mode_TXT;
    lv_obj_t *pos_back;
    lv_obj_t *angle_Reset;
    lv_obj_t *angle_run;
} angle_mode_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_27;
    lv_obj_t *pos_set_mode_TXT;
    lv_obj_t *menu_6;
    lv_obj_t *container_21;
    lv_obj_t *textarea_30;
    lv_obj_t *spinbox_32;
    lv_obj_t *spinbox_32_left_btn;
    lv_obj_t *spinbox_32_right_btn;
    lv_obj_t *slider_11;
    lv_obj_t *container_22;
    lv_obj_t *textarea_31;
    lv_obj_t *spinbox_33;
    lv_obj_t *spinbox_33_left_btn;
    lv_obj_t *spinbox_33_right_btn;
    lv_obj_t *slider_12;
    lv_obj_t *container_23;
    lv_obj_t *textarea_32;
    lv_obj_t *spinbox_34;
    lv_obj_t *spinbox_34_left_btn;
    lv_obj_t *spinbox_34_right_btn;
    lv_obj_t *slider_13;
    lv_obj_t *container_24;
    lv_obj_t *textarea_33;
    lv_obj_t *spinbox_35;
    lv_obj_t *spinbox_35_left_btn;
    lv_obj_t *spinbox_35_right_btn;
    lv_obj_t *slider_14;
    lv_obj_t *container_25;
    lv_obj_t *textarea_34;
    lv_obj_t *spinbox_36;
    lv_obj_t *spinbox_36_left_btn;
    lv_obj_t *spinbox_36_right_btn;
    lv_obj_t *slider_15;
    lv_obj_t *container_26;
    lv_obj_t *textarea_35;
    lv_obj_t *spinbox_37;
    lv_obj_t *spinbox_37_left_btn;
    lv_obj_t *spinbox_37_right_btn;
    lv_obj_t *slider_16;
    lv_obj_t *pos_run;
    lv_obj_t *pos_reset;
} pose_mode_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_28;
    lv_obj_t *traject_mode_txt;
} trajectory_planning_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_29;
    lv_obj_t *arm_information_txt;
} arm_information_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_30;
    lv_obj_t *adv_setting_txt;
} advanced_settings_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *button_8;
    lv_obj_t *about_txt;
    lv_obj_t *tileview_3;
    lv_obj_t *textarea_27;
    lv_obj_t *textarea_28;
    lv_obj_t *image_1;
} About_t;


typedef struct {
    bool auto_del;
    robot_hello_t robot_hello;
    robot_home_t robot_home;
    angle_mode_t angle_mode;
    pose_mode_t pose_mode;
    trajectory_planning_t trajectory_planning;
    arm_information_t arm_information;
    advanced_settings_t advanced_settings;
    About_t About;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline robot_hello_t *robot_hello_get(ui_manager_t *ui)
{
    return &ui->robot_hello;
}

static inline robot_home_t *robot_home_get(ui_manager_t *ui)
{
    return &ui->robot_home;
}

static inline angle_mode_t *angle_mode_get(ui_manager_t *ui)
{
    return &ui->angle_mode;
}

static inline pose_mode_t *pose_mode_get(ui_manager_t *ui)
{
    return &ui->pose_mode;
}

static inline trajectory_planning_t *trajectory_planning_get(ui_manager_t *ui)
{
    return &ui->trajectory_planning;
}

static inline arm_information_t *arm_information_get(ui_manager_t *ui)
{
    return &ui->arm_information;
}

static inline advanced_settings_t *advanced_settings_get(ui_manager_t *ui)
{
    return &ui->advanced_settings;
}

static inline About_t *About_get(ui_manager_t *ui)
{
    return &ui->About;
}


void robot_hello_create(ui_manager_t *ui);
void robot_home_create(ui_manager_t *ui);
void angle_mode_create(ui_manager_t *ui);
void pose_mode_create(ui_manager_t *ui);
void trajectory_planning_create(ui_manager_t *ui);
void arm_information_create(ui_manager_t *ui);
void advanced_settings_create(ui_manager_t *ui);
void About_create(ui_manager_t *ui);

extern lv_font_t *fs_montserratmedium_16;
extern lv_font_t *fs_montserratmedium_15;
extern lv_font_t *fs_montserratmedium_14;
extern lv_font_t *fs_montserratmedium_20;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
